version: '3'
services:
  postgresql:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: P@ssw0rd123
      POSTGRES_DB: bookApp
    networks:
      - application
    volumes:
      - pg-data:/var/lib/posgresql/data
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    networks:
    - application
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.org
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - '80:80'
    depends_on:
      - postgresql
  BooksApp:
    image: bookapp:var1
    networks:
      - application
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: postgres://postgres:P@ssw0rd123@postgresql:5432/bookApp?pool_max_conns=10
    depends_on:
      - postgresql
networks:
  application:
    driver: bridge

volumes:
  pg-data:
    driver: local
